const DB_NAME="stockflow_db",DB_VERSION=1;let db,page="dashboard";
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=e=>{const d=e.target.result;if(!d.objectStoreNames.contains("products"))d.createObjectStore("products",{keyPath:"id",autoIncrement:true});if(!d.objectStoreNames.contains("sales")){const s=d.createObjectStore("sales",{keyPath:"id",autoIncrement:true});s.createIndex("date","date")}};r.onsuccess=()=>{db=r.result;resolve()};r.onerror=()=>reject(r.error)})}
function req(store,mode,method,arg){return new Promise((res,rej)=>{let r=db.transaction(store,mode).objectStore(store)[method](arg);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
const all=s=>req(s,"readonly","getAll"),put=(s,o)=>req(s,"readwrite","put",o);
const money=n=>"৳"+Number(n||0).toLocaleString("en-BD"),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const stock=p=>(p.colours||[]).reduce((a,c)=>a+(c.sizes||[]).reduce((b,z)=>b+z.qty,0),0);
function toast(x){let t=$("#toast");t.textContent=x;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2300)}
function closeModal(){$("#modal").classList.remove("show");$("#modalBox").innerHTML=""}
function openModal(html){$("#modalBox").innerHTML=html;$("#modal").classList.add("show")}
function productHTML(p){return `<div class="product"><div><h3>${esc(p.name)}</h3><span class="muted">${stock(p)} units · ${p.colours.length} colour(s)</span><div class="chips">${p.colours.map(c=>`<span class="chip"><b>${esc(c.name)}</b>: ${(c.sizes||[]).filter(z=>z.qty>0).map(z=>z.size+" "+z.qty).join(" · ")||"out of stock"}</span>`).join("")}</div></div><div><button class="sell" data-sell="${p.id}">Sell</button> <button class="secondary" data-edit="${p.id}">Edit</button></div></div>`}
async function render(){const ps=await all("products"),ss=await all("sales");const meta={dashboard:["Dashboard","Overview of your stock and sales"],inventory:["Inventory","Manage products, colours, sizes and stock"],sales:["Sales History","Every completed sale is stored locally"],reports:["Reports","Sales and inventory summary"],settings:["Settings","Backup and manage local data"]}[page];$("#title").textContent=meta[0];$("#sub").textContent=meta[1];$$(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===page));if(page==="dashboard")dash(ps,ss);if(page==="inventory")inventory(ps);if(page==="sales")sales(ss);if(page==="reports")reports(ps,ss);if(page==="settings")settings()}
function dash(ps,ss){const today=new Date().toISOString().slice(0,10),ts=ss.filter(s=>s.date.slice(0,10)===today),rev=ss.reduce((a,s)=>a+s.total,0);$("#content").innerHTML=`<div class="stats"><div class="stat"><small>PRODUCTS</small><strong>${ps.length}</strong></div><div class="stat"><small>AVAILABLE STOCK</small><strong>${ps.reduce((a,p)=>a+stock(p),0)}</strong></div><div class="stat"><small>TODAY'S SALES</small><strong>${ts.reduce((a,s)=>a+s.qty,0)}</strong></div><div class="stat"><small>TOTAL REVENUE</small><strong>${money(rev)}</strong></div></div><div class="grid"><div class="card"><h2>Inventory</h2>${ps.map(productHTML).join("")||'<div class="empty">No products yet.</div>'}</div><div class="card"><h2>Recent sales</h2>${salesTable(ss.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,8))}</div></div>`;bindProductButtons()}
function inventory(ps){$("#content").innerHTML=`<div class="toolbar"><input id="search" class="search" placeholder="Search product or colour"></div><div id="list">${ps.map(productHTML).join("")||'<div class="card empty">No products yet. Click Add Product to begin.</div>'}</div>`;bindProductButtons();$("#search").oninput=async()=>{const q=$("#search").value.toLowerCase(),a=await all("products");$("#list").innerHTML=a.filter(p=>JSON.stringify(p).toLowerCase().includes(q)).map(productHTML).join("")||'<div class="card empty">No matches.</div>';bindProductButtons()}}
function bindProductButtons(){$$("[data-sell]").forEach(b=>b.onclick=()=>sell(Number(b.dataset.sell)));$$("[data-edit]").forEach(b=>b.onclick=()=>openProduct(Number(b.dataset.edit)))}
function salesTable(a){return a.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Date</th><th>Product</th><th>Colour</th><th>Size</th><th>Qty</th><th>Price</th><th>Total</th></tr></thead><tbody>${a.map(s=>`<tr><td>${new Date(s.date).toLocaleString()}</td><td>${esc(s.name)}</td><td>${esc(s.colour)}</td><td>${s.size}</td><td>${s.qty}</td><td>${money(s.price)}</td><td><b>${money(s.total)}</b></td></tr>`).join("")}</tbody></table></div>`:'<div class="empty">No sales yet.</div>'}
function sales(a){a=a.slice().sort((x,y)=>y.date.localeCompare(x.date));$("#content").innerHTML=`<div class="card">${salesTable(a)}</div>`}
function reports(ps,ss){const by={};ss.forEach(s=>by[s.name]=(by[s.name]||0)+s.total);$("#content").innerHTML=`<div class="stats"><div class="stat"><small>UNITS SOLD</small><strong>${ss.reduce((a,s)=>a+s.qty,0)}</strong></div><div class="stat"><small>REVENUE</small><strong>${money(ss.reduce((a,s)=>a+s.total,0))}</strong></div><div class="stat"><small>STOCK</small><strong>${ps.reduce((a,p)=>a+stock(p),0)}</strong></div><div class="stat"><small>TRANSACTIONS</small><strong>${ss.length}</strong></div></div><div class="card"><h2>Revenue by product</h2>${Object.entries(by).map(([n,v])=>`<div class="summary"><span>${esc(n)}</span><b>${money(v)}</b></div>`).join("")||'<div class="empty">No sales yet.</div>'}</div>`}
function settings(){$("#content").innerHTML=`<div class="grid"><div class="card"><h2>Backup</h2><p class="muted">Export your local inventory and sales database.</p><button id="backup" class="primary">Export Backup</button></div><div class="card"><h2>Restore</h2><p class="muted">Restore a StockFlow JSON backup.</p><input id="restore" type="file" accept=".json"></div></div>`;$("#backup").onclick=backup;$("#restore").onchange=e=>restore(e.target.files[0])}
async function openProduct(id=null){let p=null;if(id){p=(await all("products")).find(x=>x.id===id);if(!p)return}const initial=p?.colours?.length?p.colours:[{name:"",sizes:["XS","S","M","L","XL","XXL"].map(size=>({size,qty:0}))}];openModal(`<h2>${p?"Edit Product":"Add Product"}</h2><form id="productForm"><div class="field"><label>PRODUCT NAME</label><input id="productName" required value="${esc(p?.name||"")}" placeholder="e.g. Dior"></div><div class="field"><label>COLOURS & STOCK</label><div id="colours"></div><button type="button" id="addColour" class="secondary">＋ Add Colour</button></div><div class="modal-foot"><button type="button" id="cancel" class="secondary">Cancel</button><button type="submit" class="primary">Save Product</button></div></form>`);
const box=$("#colours");initial.forEach(c=>addColourRow(box,c));$("#addColour").onclick=()=>addColourRow(box);$("#cancel").onclick=closeModal;
$("#productForm").onsubmit=async e=>{e.preventDefault();try{const name=$("#productName").value.trim();const colours=[...box.querySelectorAll(".colour")].map(c=>({name:c.querySelector(".colourName").value.trim(),sizes:[...c.querySelectorAll("[data-size]")].map(x=>({size:x.dataset.size,qty:Math.max(0,parseInt(x.value||"0",10))})).filter(x=>x.qty>0)})).filter(c=>c.name);if(!name)return toast("Enter a product name.");if(!colours.length)return toast("Add at least one colour with stock.");const obj={...(p||{}),name,colours,updatedAt:new Date().toISOString()};await put("products",obj);closeModal();toast("Product saved successfully");await render()}catch(err){console.error(err);toast("Could not save product.")}}}
function addColourRow(box,c={name:"",sizes:["XS","S","M","L","XL","XXL"].map(size=>({size,qty:0}))}){const d=document.createElement("div");d.className="colour";d.innerHTML=`<div style="display:flex;gap:8px"><input class="colourName" required placeholder="Colour e.g. Olive" value="${esc(c.name)}"><button type="button" class="danger removeColour">Remove</button></div><div class="sizes">${c.sizes.map(z=>`<div class="size"><label>${z.size}</label><input data-size="${z.size}" type="number" min="0" step="1" value="${z.qty}"></div>`).join("")}</div>`;box.appendChild(d);d.querySelector(".removeColour").onclick=()=>d.remove()}
async function sell(id){const p=(await all("products")).find(x=>x.id===id);if(!p)return;openModal(`<h2>Record Sale</h2><div class="notice">Available stock will be reduced automatically.</div><form id="saleForm"><div class="form-grid"><div class="field"><label>COLOUR</label><select id="saleColour">${p.colours.map((c,i)=>`<option value="${i}">${esc(c.name)}</option>`).join("")}</select></div><div class="field"><label>SIZE</label><select id="saleSize"></select></div><div class="field"><label>QUANTITY</label><input id="saleQty" type="number" min="1" value="1" required></div><div class="field"><label>PRICE / UNIT (৳)</label><input id="salePrice" type="number" min="0" step=".01" required></div></div><div id="available" class="muted"></div><div class="modal-foot"><button type="button" id="cancel" class="secondary">Cancel</button><button class="primary">Confirm Sale</button></div></form>`);const refresh=()=>{const c=p.colours[+$("#saleColour").value],valid=c.sizes.filter(z=>z.qty>0);$("#saleSize").innerHTML=valid.map(z=>`<option value="${z.size}">${z.size} — ${z.qty} available</option>`).join("");$("#available").textContent=valid.length?`Available: ${valid.find(z=>z.size===$("#saleSize").value)?.qty||0}`:"No stock"};$("#saleColour").onchange=refresh;$("#saleSize").onchange=refresh;$("#cancel").onclick=closeModal;refresh();$("#saleForm").onsubmit=async e=>{e.preventDefault();const c=p.colours[+$("#saleColour").value],size=$("#saleSize").value,z=c.sizes.find(x=>x.size===size),qty=+$("#saleQty").value,price=+$("#salePrice").value;if(!z||qty<1||qty>z.qty)return toast("Not enough stock.");z.qty-=qty;await put("products",p);await put("sales",{date:new Date().toISOString(),productId:p.id,name:p.name,colour:c.name,size,qty,price,total:qty*price});closeModal();toast("Sale recorded");render()}}
async function backup(){const data={version:1,exportedAt:new Date().toISOString(),products:await all("products"),sales:await all("sales")};const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));a.download="stockflow-backup-"+new Date().toISOString().slice(0,10)+".json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function restore(file){if(!file)return;try{const d=JSON.parse(await file.text());if(!Array.isArray(d.products)||!Array.isArray(d.sales))throw 0;if(!confirm("Replace current local data with this backup?"))return;const t=db.transaction(["products","sales"],"readwrite");t.objectStore("products").clear();t.objectStore("sales").clear();t.oncomplete=async()=>{for(const p of d.products)await put("products",p);for(const s of d.sales)await put("sales",s);toast("Backup restored");render()}}catch(e){toast("Invalid backup file")}}
$$(".nav").forEach(n=>n.onclick=()=>{page=n.dataset.page;render();$("#side").classList.remove("open")});$("#addTop").onclick=()=>openProduct();$("#menu").onclick=()=>$("#side").classList.toggle("open");$("#modal").onclick=e=>{if(e.target.id==="modal")closeModal()};
openDB().then(render).catch(e=>{console.error(e);toast("Local database could not be opened.")});if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(console.warn));